# Set filename without extension for consistency.
name: release.changelogs

on:
  pull_request:
    branches:
      develop
jobs:
  test:
    name: create.changelogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initial
        run: This event is a pull request that had an assignee removed.
      
      - name: Create Log
        run: make release
